# data_schemas.py
import pandera.pandas as pa
from pandera.typing import Series


# Define a DataFrame model for probate/estate data
class ProbateSchema(pa.DataFrameModel):
    fiduciary_number: Series[str] = pa.Field(nullable=True)
    court_file_number: Series[str] = pa.Field(nullable=True)
    estate_number: Series[str] = pa.Field(nullable=True)
    case_number: Series[str] = pa.Field(nullable=True)
    county_jurisdiction: Series[str] = pa.Field(nullable=True)
    date_of_filing: Series[str] = pa.Field(nullable=True)
    date_of_will: Series[str] = pa.Field(nullable=True)
    type: Series[str] = pa.Field(nullable=True)
    status: Series[str] = pa.Field(nullable=True)
    will: Series[str] = pa.Field(nullable=True)
    decedent: Series[str] = pa.Field(nullable=True)
    date_of_death: Series[pa.Timestamp] = pa.Field(nullable=True)
    decedent_address: Series[str] = pa.Field(nullable=True)
    executor_first_name: Series[str] = pa.Field(nullable=True)
    executor_last_name: Series[str] = pa.Field(nullable=True)
    administrator_first_name: Series[str] = pa.Field(nullable=True)
    administrator_last_name: Series[str] = pa.Field(nullable=True)
    pow_first_name: Series[str] = pa.Field(nullable=True)
    pow_last_name: Series[str] = pa.Field(nullable=True)
    subscriber_first_name: Series[str] = pa.Field(nullable=True)
    subscriber_last_name: Series[str] = pa.Field(nullable=True)
    pr_first_name: Series[str] = pa.Field(nullable=True)
    pr_last_name: Series[str] = pa.Field(nullable=True)
    pr_address: Series[str] = pa.Field(nullable=True)
    pr_city: Series[str] = pa.Field(nullable=True)
    pr_state: Series[str] = pa.Field(nullable=True)
    pr_zip: Series[int] = pa.Field(nullable=True)
    heir_1_first_name: Series[str] = pa.Field(nullable=True)
    heir_1_last_name: Series[str] = pa.Field(nullable=True)
    relationship_1: Series[str] = pa.Field(nullable=True)
    age_1: Series[int] = pa.Field(nullable=True)
    address_1: Series[str] = pa.Field(nullable=True)
    city_1: Series[str] = pa.Field(nullable=True)
    state_1: Series[str] = pa.Field(nullable=True)
    zip_1: Series[int] = pa.Field(nullable=True)
    attorney_first_name: Series[str] = pa.Field(nullable=True)
    attorney_last_name: Series[str] = pa.Field(nullable=True)
    attorney_address: Series[str] = pa.Field(nullable=True)
    attorney_city: Series[str] = pa.Field(nullable=True)
    attorney_state: Series[str] = pa.Field(nullable=True)
    attorney_zip: Series[int] = pa.Field(nullable=True)
    url: Series[str] = pa.Field(nullable=True)
    aggregated: Series[str] = pa.Field(nullable=True)
